### ISSUE TITLE
CAN BUS magnetic heading sensor

### ISSUE THREAD

**Issue by GrahamStallard** [iltis42/XCVario#112]
Really like the design of this unit.
Had trouble calibrating CAN BUS sensor.
Put this down to user error. Re-read manual multiple times.
Completed calibration process incrementally as per manual on the bench. All working. 
Switched on and off multiple times on the bench. All good.
Installed in glider the same day.
Switched on and off multiple times on the bench. All good.
Next day ridge flying.
Rigged and powered up panel. 
Self-test fails CAN. Compass would fail.
CAN indicator greyed out.
Switched off and on several times. Still failing CAN test.
FLARM working.
Flight is not dependant on XCVario.
Fly. Great ridge day.
Notice while flying the CAN symbol blue at times. Also, at times there is a magnetic direction.
Not sure what the root cause is as XCVario and sensor are new. All connections are good. Cable is a known good cable. 
My next step is swap in an RS232 sensor. Cable is 2M.
The issue seems to be with the CAN BUS in the XCVario unit. Not sure if the CAN BUS test bus needs a CAN device connected. The XCVario may have a loopback to test without devices connected. I did not try this last thing.
If I can help investigate this issue, I am comfortable to assist.
Best Regards,
Graham

**Comment by iltis42** [comment]
In fact the selfTest is using the hardware loopback feature of the device and loops back this.
Meanwhile we could reproduce and have seen a timing issue in CAN bus selftest, covered by this changeset:
https://github.com/iltis42/XCVario/commit/490684eed64189388e5f94ae33f0dc0b44cb8eed
Here is the new build that fixes CAN selfTest:  https://github.com/iltis42/XCVario/blob/master/images/sensor-master-21.1130-0024.bin
Please give us feedback if solved also in your installation. Thanks !

**Comment by GrahamStallard** [comment]
Hello Eckhard,

 

            Thank you for prompt reply. I did wonder if the sensor was used for a loopback test. I did try different the CAN BUS at 500K.

 

            Understand and will update firmware. Will let you know how I get on.

 

 

 

Best Regards,

 

Graham Stallard.

 

Mobile 07801 387154

**Comment by iltis42** [comment]
The external sensor is not used at loopback test, hence could disturb exactly this as it carries out a loobpack as well (while looping, the chip sends its data on the wire), and beside that it probes different CAN bus rates (sending its data, waiting for ack), what can impact the self test at head end by accident. Things are aggravated when you power on the vario by the main fuse.
Thanks for reporting, this is the feedback we need, @hjr reported this problem as well from South Africa this morning what should have been the same thing. No i have solved this a bit modified timing, clearing of receive queue, using another length for selftest on head end, and more time to catch the packets at the correct data rate from the sensor.

**Comment by GrahamStallard** [comment]
Understood.

Best Regards,
Graham.
Mobile 07801 387154
