### ISSUE TITLE
Connected FLARM stops transmitting

### ISSUE THREAD

**Issue by GrahamStallard** [iltis42/XCVario#113]
Second day flying the ridge.
XCVario used to increase familiarity of operation. FLARM function very useful.
FLARM function working. Active a lot the previous day and initially this day.
After approx. 1.5 hours’ notice not ‘seeing’ other gliders on my FLARM radar (XCSoar) or XCVario.
Observe only the GPS LED is lit on the LXNAV FlarmLED+ display. No pulse on TX LED.
Switch XCVario off and on several times (reboot both LXNAV PowerMouse and XCVario).
Condition remains.
Land.
Go home.
Next day investigate.
Power up panel including XCVario and FLARM.
Only the GPS LED is lit on the LXNAV FlarmLED+ display. No pulse on TX LED.
The LXNAV FlarmLED+ display during bootup displays as usual.
Power FLARM directly. Boots up and works! Not what I was expecting.
Reconnect FLARM via XCVario and power.
All working? Also unexpected.
The LXNAV PowerMouse has been working through an LXNAV S100 for some 2 months before swapping out for XCVario.
Puzzled as the connections are power and RS232. Power does not seem to be the issue as both units power up OK. That leaves the RS232 signal. 
Puzzled as to root cause.
XCVario firmware was October 2021 (1)
Have now updated OTA to the latest release NOV(1). 
See NOV (2) 21.1124-2125 is now available. Will update OTA with this before flying.
Waiting for another opportunity to fly to check.
Work around should the issue reappear. Land. Power FLARM direct.

**Comment by iltis42** [comment]
Sounds also like cabling problem. For ADSB Flarm modules we recommend also to powered by its own cables,
not via XCVario RJ45, the current might be too high to run reliably over this connector, and its always
better to have an own fuse for each device and option to power cycle in flight or even power down when
running short in battery. Keep us updated on reappear.

**Comment by GrahamStallard** [comment]
OK. Understand. Will adjust wiring accordingly. Will do. Thank you.

**Comment by GrahamStallard** [comment]
Hello Eckhard,

 

            Thank you for prompt reply. Put reply on GitHub.

 

 

Best Regards,

 

Graham Stallard.

 

Mobile 07801 387154

**Comment by iltis42** [comment]
Closed, no more requests after support for wring given, obviously thing's work now, Power Flarm is also working at hundreds of other installation flawless.

**Comment by GrahamStallard** [comment]
👍

Best Regards,
Graham.
Mobile 07801 387154
