### ISSUE TITLE
Make working Flarm connection visible in System configuration/Check different baud rates in Flarm configuration

### ISSUE THREAD

**Issue by volkmarnissen** [iltis42/XCVario#132]
Current Situation:
I have a flarm device connected to xcvario. I don't know the baud rate.
How can I check whether communication xcvario- flarm works?
It is cumbersume to find out the baud rate of the attached flarm.

Proposals:
1. Add a "Flarm status" to the System configuration which shows 
- Flarm connection is working (at baud rate  xyz)
- GPS data in Flarm available

2. Do automatic selection of baud rate
Other devices which use flarm data (Rechenknecht) have an automated approach. They check different baud rates automatically and find out the baud rate of the flarm device automatically by checking the common values.9600, 19200...

If this makes sense, I could try to implement it.

**Comment by iltis42** [comment]
Regarding the two points:
1) There is already an indication if FLARM connection is working, its the Wifi or Bluetooth symbol what changes partly to green color once there is NMEA traffic from FLARM:
https://xcvario.de/handbuch#__RefHeading___Toc226_1394872305
2) Baudrate detection unfortunately is not possible, reason: ESP32/UART is not working correctly (or even at all) after altering setting in the UART registers online, and there is no separate reset line of the UART peripheral, means a reset of the whole embedded system was required. Even worse, some also crucial UART settings e.g. pin twisting wont work after reboot and needed power on restart, and cannot be altered except pressing the power button. So in flight, this is of course the last thing desired, e.g. if FLARM goes offline in flight (switched off, defect, fuse blown, cable issue), we don't want to end up with a rebooting variometer, possibly requiring also manual power ON reset either, so this feature needs to be rejected as of hardware restrictions.

**Comment by volkmarnissen** [comment]
You are right with both points.

However, would it make sense to mention the "green dot"  in the chapter about the baud rate (https://xcvario.de/handbuch#__RefHeading___Toc2289_3622479183)?
Alternatively, one could refer to the corresponding chapter (https://xcvario.de/handbuch#__RefHeading___Toc226_1394872305)   
I read the complete manual, but was not aware of it when it came to installation/configuration.

The green dot makes it really easy to find the right baud rate and is a good alternative to automatism.
You just configure one baud rate, check the green dot. If it's green you found the correct baud rate,
otherwise try the next one. You have the correct baud rate in 5 minutes or less.

**Comment by iltis42** [comment]
No issue to add a quick reference in the baud rate chapter regarding FLARM status display, will add this for a new revision.
The RS-232 serial protocol from the early sixties features no native handshake mechanism to exchange datarate, this is unfortunately an item to be pre-configured. Mechanism to "autodetect" baudrate are based on a trial an error mechanism, and thats what we need to do here manually as you describe. Usually the FLARM comes with a factory default, or in case altered by the user, the one should be aware what baudrate is to be set. Any other defaults are designed to work together with any FLARM out of the box, what is true also for the standard baud rate of 19.2 Kbaud (the default for S1 in XCVario), either.
