### ISSUE TITLE
Weather data in XCSoar / Second Wifi Adapter

### ISSUE THREAD

**Issue by volkmarnissen** [iltis42/XCVario#135]
It would be nice to have current weather data in xcsoar, but this is often not possible, because the XCsoar device is connected to xcvarios wifi and can't use GSM/LTE... .

Proposal: If the xcvario hardware had two wifi devices, one, could act as a wifi client and proxy the data from any wifi hotspot to the xcsoar device. I don't know, whether this is possible.
Additional benefit:
The WIFI client could also easily used for software updates, since it is connected to the internet.

**Comment by iltis42** [comment]
The hardware does not support a second WiFi device, so this is not possible, so closed as there is no option as of today.
Beside this idea, there are the following options, available already now:
There is no issue to use the bluetooth interface to interconnect XCVario, so WiFi is free and may get connected to a personal internet hotspot. 
Local mobile data of course is a further option, in case xcsoar device supports sim card.
