### ISSUE TITLE
XCS MC sync to XCV over serial S2

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#145]
The MC changes on XCS side do not propagate to XCV as they did in the past.

It still does work using BT connectivity. The S2 connection does propagate MC from XCV to XCS and XCVario protocol is Ok.

XCSoar on Android 9
XCV rev 29.12.2021
Serial/USB dongle on OTG Hub plugged to S2
 
The HUB is also a new change since last time I witnessed things working, but the HUB does work fine for eg USB stick, 5V charge. So I expect a full duplex functionality with the serial dongle.

**Comment by iltis42** [comment]
What is exactly the Android version of xcsoar ?
Problem can reproduced with 7.21 Android (not the playstore version), but from xcsoar Android download webpage.
No problem with older PlayStore version 7.20 and also using v7.21-Linux~git#1caa118964 on PC.
Nothing comes in on data monitor, on xcvario side, so likely nothing is sent. Other problems are reported as well
with that version, e.g. sendNMEA doesn't work with .xpi and there are digits cut from cambridge ballast altering sentence.
Using serial monitor, and sending !g,b<N> absence of problem can be demonstrated.
Issue is considered in xcsoar, maybe a glitch in 7.21 Android, so it may make sense to build a recent version for Android, and if no glitch, a bug report there should be beneficial.
