### ISSUE TITLE
Since 4bf9674ffaf7dc5abe3c678598ec761ff4db4c2b, not buildable

### ISSUE THREAD

**Issue by CazYokoyama** [iltis42/XCVario#172]
The error message is

/home/caz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/ESP32-OTA-Webserver/libESP32-OTA-Webserver.a(MyWiFi.cpp.obj):(.literal._Z17start_dhcp_serverv+0x8): undefined reference to `dhcps_set_option_info(unsigned char, void*, unsigned int)'
/home/caz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/ESP32-OTA-Webserver/libESP32-OTA-Webserver.a(MyWiFi.cpp.obj):(.literal._Z17start_dhcp_serverv+0xc): undefined reference to `dhcps_dns_setserver(ip_addr const*)'
/home/caz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/ESP32-OTA-Webserver/libESP32-OTA-Webserver.a(MyWiFi.cpp.obj): in function `start_dhcp_server()':
/home/caz/esp/esp-idf/examples/get-started/XCVario/components/ESP32-OTA-Webserver/MyWiFi.cpp:127: undefined reference to `dhcps_set_option_info(unsigned char, void*, unsigned int)'
/home/caz/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/caz/esp/esp-idf/examples/get-started/XCVario/components/ESP32-OTA-Webserver/MyWiFi.cpp:131: undefined reference to `dhcps_dns_setserver(ip_addr const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sensor.elf.dir/build.make:446: sensor.elf] Error 1
make[1]: *** [CMakeFiles/Makefile2:2133: CMakeFiles/sensor.elf.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
make failed with exit code 2

BTW, thank you for picking my complain about IP address. You change 192.168.0.1 -> 192.168.4.1

**Comment by iltis42** [comment]
This unresolved symbol is out of scope of XCVario repo, and might be linked with your IDF version used.
The DNS server setting (to zero), need and also secured WiFi, as unsecured open WiFi doesn't work anymore with latest Android phones for software download.

I have checkedout: 

gittest3@hp:~/esp/esp-idf$ git branch
  master
  release/v3.1
* **release/v4.3**
  v4.3

Can you crosscheck it yours is same and if you can find the code in here:

git@hp:~/esp/esp-idf$ find . -name "*.c" |xargs grep dhcps_dns_setserver
./components/esp_netif/lwip/esp_netif_lwip.c:            dhcps_dns_setserver(lwip_ip);

**Comment by Steffen-Engel** [comment]
I've had the same struggle.

solved with namespace definition in components/lwip/include/apps/dhcpserver/dhcpserver.h

not sure if this is the right way to fix it, always had a struggle with the idea of namespaces

```
#ifdef __cplusplus
extern "C" {
#endif

[...]

#ifdef __cplusplus
} // extern "C"
#endif
```

**Comment by hjr** [comment]
Same issue here. I could resolve it by those steps:
- pull the latest v4.3 esp-idf version from v4.3 branch: git pull ; git submodule update --recursive
- run the idf install script to update python modules etc.: ./install.sh
- and in your XCV project dir then first do a: idf.py fullclean
from then on my build was Ok again.
thx

**Comment by MoskitoAndi** [comment]
Same Problem, idf Version is 
ESP-IDF v4.4-dev-4-g73db142403-dirty

**Comment by iltis42** [comment]
Okay, issue is now clear, old 4.3 or even wrong (4.4) version used. Solution as above.

**Comment by hjr** [comment]
The -dirty meas that your idf git dump is modified, most probably the
submodules are not in sync.

Am Mittwoch, dem 09.02.2022 um 12:37 +0000 schrieb Andreas Titze:

**Comment by CazYokoyama** [comment]
Confirm hjr's procedure works. Thx. I suspect idf.py fullclean is a key.

**Comment by iltis42** [comment]
Have made a QR code for WiFi here: https://www.qr-code-generator.com/solutions/wifi-qr-code/ (tapped the Wifi symbol)
that should connect to it. Scanning this with a QR code scan app on my mobile won't open the Wifi or populate on my Xiaomi mobile. Any idea what i am missing ?

![Screenshot from 2022-02-10 09-39-23](https://user-images.githubusercontent.com/34288016/153369369-061eb998-7521-4258-9315-e28ce12d48bc.png)
