### ISSUE TITLE
Use static pressure instead of compensated pressure when motor is running

### ISSUE THREAD

**Issue by volkmarnissen** [iltis42/XCVario#174]
Yesterday, I was on a longer flight using motor. 
The XCVario showed permanently 5m/s or more. Which was totally wrong.
Most likely this was because the vario calculates the climb ratio from the compensated nozzle which is influenced by the propeller.

A Flarm with ENL is attached to the vario. 
What do you think about an **additional mode "ENL Auto" mode for "Electronic Compensation" in setup?** This mode, will configur xcvario to use TK compensation, when motor is of, otherwise electronic compensated (or no compensation) will be used?
One can get the information whether the motor is running by reading flarm ENL data.

**Comment by iltis42** [comment]
Not too much, as not only TE pressure is impacted by the propeller.  Electronic compensation won't work either as the equations assume constant Total Energy (TE), what is not the case when energy is added by motor. 
You may first try to enable "Electronic Compensation" manually and check if there is a change, and if this helps out post again.

**Comment by volkmarnissen** [comment]
yesterday, I tried the electronic compensation. There is a change, but it is not sufficient. Instead of showing permanently more than 5m/s the vario shows now 3,5-4,5 m/s.

Is it possible to have an additional entry in the vario menu named "motor" having two options:
default: "Use static pressure for vario, when motor is running"?
"compensate allways" (even if motor is running).

May be it is also possible to implement this without a menu entry, because it makes no sense to use TE compensation together with a running engine.
My former glider (ASH26e) had a LX navigation vario (EOS/ERA). It worked perfectly when engine was running without any configuration. I don't know how, but I was happy about it. :-)

**Comment by iltis42** [comment]
Unfortunately the ENL is part of the igc file, what is created to be downloaded _after_ flight, but not part of flarm protocol, so i see nothing what i can to for that while your glider is still in flight.
In my opinion there is another issue in your glider, i have not seen this problem in other self-starters where XCVario shows _exactly_ the climb they have, even the motor is blowing exactly to the TE probe. Maybe there is leak, tubes are twisted or something, can you first do the usual leak tests and crosscheck your connections to exclude an error there.
The picture you see might indicate a twist of TE and ST port at the variometer. 
I agree, it could be helpful to try an EOS/ERA in your current glider, to see the result there, guess at the same pressure both will show the same. BTW,  is your mechanical vario connected to the same pressure and what does this say?

**Comment by volkmarnissen** [comment]
Hi,

OK, I'll check the tubes. As of now I didn't use the new glider
for soaring. So, there is a good chance that something is wrong in the
tubing.
I have no EOS/ERA and I have no mechanical vario.

Am Mi., 2. März 2022 um 10:10 Uhr schrieb Eckhard Völlm <
***@***.***>:
