### ISSUE TITLE
Aircraft Switches

### ISSUE THREAD

**Issue by lordfolken** [iltis42/XCVario#177]
I would  love to add aircraft switches such as:
- gear 
- air breaks
- canopy lock
- tow hook lock/unlock
- tail dolly sensor
- trim position sensor
- water lever
- event for logger

**Comment by lordfolken** [comment]
Potentially this could be implemented with a I2C or CAN device, with a certain ammount of connectors?

**Comment by iltis42** [comment]
Guess you mean general purpose input ports (GPI), either digital or analog for the above purposes.
In terms of hardware, maybe the design we have for the CAN magnetsensor could fit. There is already an ESP32-C3 with several ports that can serve for this purpose.
