### ISSUE TITLE
Water ballast synch between XCV and XCS

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#202]
Any activity that provocs water ballast synch between XCS and XCV still produces the already reported exploded water ballast settings. Eg dumping water results in multiple 1000l of water ballast on either side, XCS or XCV. 
Throughout using the badly designed CAI !g NMEA protocol snippets to synch water ballast this issue is still not solved.

**To Reproduce**
Use the two seater setup, with master and slave XCV connected by CAN. Each XCV connected to XCS with the S2 port.
1. Change water ballast setting on one of the four nodes will produce the propagation escalation, or at least a significantly different ballast setting on other nodes.

**Expected behavior**
Any configuration of water ballast should propagate to all three other nodes, resulting in the same amount of liters ballast on all four nodes.

**Versions**
XCS 7.23; XCV 2207'ish

**Additional context**
For the communication with XCS the !g NMEA sentences should be discouraged and a better NMEA protocol put in place.

**Comment by iltis42** [comment]
For Borgelt and Cambridge Protocol users, there will be no solution, as this protocols are fix.
XCVario protocol now is using a more precise !g message using float format what should be part of XCV 7.23 (https://github.com/XCSoar/XCSoar/pull/773), so IMHO the pimped  !g should not the culprit, also the upstream NMEA had be pimped to a 3 digits (
sprintf(str,"$PXCV,%3.1f,%1.2f,%d,**%1.3f**,%d,%2.1f,%4.1f,%4.1f,%.1f", te, mc, bugs, bal, ..), what solve the issue on my desk (polar) reference weight and crew weight (separate open issue), are in perfect sync what might be not for good reason (today you can manually adjust this everywhere to produce this problem).  
So i see two places to improve: 
1) Add warrants for synchronisation of all weights and also wing-area, as already started for crew weight, and IMHO we need to sync the reference weight (and wing area) from polar file as well with XCVario, and once this is consistent (today you need ensure this consistency e.g. when changing polar or crew weight on each places) the problem maybe already absent.
2) Let both peers derive its ballast overweight (whats needed to adjust the polar), calculate locally, and don't exchange this. Just exchange parameters like water ballast in kg, crew weight in kg and reference weight in kg, and live with small deviations e.g. coming from a different wing-area, reference- or crew-weights, what might also fix the water ballast dump with two devices.

**Comment by hjr** [comment]
Not asking for a nice to have improvement here, just reporting an issue that should be solvable, as you mentioned.

**Comment by iltis42** [comment]
Solution, as discussed, will be the warrant for syncronisation of all weights as from XCV side provided by https://github.com/iltis42/XCVario/issues/201 that is already in place, rest of work should be in XCSoar: 
1) Takeover of weights from new protocol messages in XCVario Protocol
2) Removal of ballast overload takeover from $PXCV field (obsolete)
3) Sending of messages in new protocol format for all three weights

**Comment by iltis42** [comment]
XCSoar 7.27 comes with new protocol version to exchange water ballast as an absolute value that solves this problem, as indicated by the two commits above. The code change of this was merged into XCSoar and issue is proved to be absent.
