### ISSUE TITLE
DG800S/15 Polar not correct

### ISSUE THREAD

**Issue by mbellorini** [iltis42/XCVario#206]
Hi,

With Reference of my own glider DG-800S, HB-3436 I believe that the DG800S/18 Polar is correct while DG800S/15 Polar has wrong Reference Wingload:

Realistic (18m):
{ 1390, "DG 800S/18", 29.97, 77.9497, -0.4760, 130.0, -0.9192, 170.0, -1.7786, 150, 11.81}
->  11.81 * 29.97 = 354kg

Wrong (15m):
{ 1370, "DG 800S/15", 34.93, 92.4983, -0.5834, 130.0, -0.9720, 170.0, -1.6852, 150, 10.68},
-> 10.68 * 34.93 = 373kg

Based on my Glider, Reference Weight 15m should be 8kg less than Reference Weight 18m

Proposal (15m):
(354 - 8) / 10.68 ) = 32.40
{ 1370, "DG 800S/15", **32.40**, 92.4983, -0.5834, 130.0, -0.9720, 170.0, -1.6852, 150, 10.68}

Thanks for considering.
Marcel

**Comment by iltis42** [comment]
The "Reference Weight", is the weight the polar was measured e.g. in an Idaflieg measurement flight, so IMHO no option to change this, unless there is a new measurement. @hjr what do you think ?

**Comment by hjr** [comment]
True, ref weight is just the weight the polar was measured with, or recalculated to. So the wish to change the ref weight does need a change of the three speed points. The change factor is sqrt(new weight/ old weight).

**Comment by iltis42** [comment]
The three speed points are married with the ref weight, if your glider has a lower wingload, what can be, e.g. if your gross weight is lower than the DG800S from measurement e.g. by a lower crew weight or empty weight of your glider, you needed to adjust there, and XCVario will do the corresponding adjustments to reflect your wingload.
