### ISSUE TITLE
Info for another lcd display

### ISSUE THREAD

**Issue by docop** [iltis42/XCVario#225]
Hi
 Very great discovery, i haven't seen your project before. Nice view for the 'red arrow' too and big number look nice. I wonder, can it be possible to change the lcd display as well ? Are you using a special library.. or it's just a matter to simply load a different one and having proper pin connected .. ? I was looking for one with the ST7789s controller.

thanks in advance

**Comment by iltis42** [comment]
The ILI9341 and ST7789 drivers are mostly the same, differences are mostly that some module with ST7789 do not support 16 bit parallel MCU mode, hence this is not used here either, so for SPI bus this should already work without changing the driver.
