### ISSUE TITLE
[Feature Request] Update SDK to one which supports ESP32S3 chips

### ISSUE THREAD

**Issue by kubark42** [iltis42/XCVario#238]
The ESP32S3 has become a fairly ubiquitous chip, with a lot of incredibly cost effective bare and featureful boards available. For development purposes, it would be nice to be able to explore some of these.

Unfortunately, the currently supported SDK (4.3) does not support the S3. This SDK is [over 2 years old](https://github.com/espressif/esp-idf/releases/tag/v4.3), it would be nice to bump it to at least 4.4 (where the S3 first appears) or, even better, something in the v5 domain. 

This might be as easy as updating the instructions at https://github.com/iltis42/XCVario/blob/master/README.txt, but even if that compiled immediately it would still be necessary to test against a live target.

**Comment by hjr** [comment]
What is the feature from the S3 chip that you are interested in?

**Comment by kubark42** [comment]
> What is the feature from the S3 chip that you are interested in?

For me, it's not the S3 chip's features so much as the things they're being packaged into:
- Mass availability at breathtakingly low prices. 
  - [On Amazon](https://www.amazon.com/AITRI3PCS-ESP32-S3-DevKitC-1-N8R2-Development-Integrates-Functions/dp/B0BX31WGQG/), three ESP32S3 dev boards for $8/ea.
- Tons of great integrated hardware from manufacturers such as [LILYGO](https://www.lilygo.cc/).
- Dev boards have two USB-C plugs, which makes them easier for me to use.

The LILYGO stuff is hard to beat. [For $30](https://www.lilygo.cc/products/t-rgb), an entire ESP32 touchscreen module which fits perfectly into a standard 2 1/4" cutout. [For $37](https://www.lilygo.cc/products/t5-4-7-inch-e-paper-v2-3), an ESP32 4.7" e-paper module, with option for integrated battery and battery charger. With these kind of fully integrated displays on the market, hardware development becomes much easier. If the only obstacle to developing on these hardware platforms is compiling the code with a more modern toolkit, that seems like a straightforward upgrade path (as opposed to jumping ship to a different uC brand/architecture).

**Comment by hjr** [comment]
Not sure, I might miss the point here.

**Comment by kubark42** [comment]
> Not sure, I might miss the point here.

Being a little bit pedantic, are you missing it or not agreeing with it? (I don't mean to be offensive, I just always like not to make assumptions about textual clarity when writing on an international forum).

Assuming that you understand my point, but you don't necessarily agree with it, here's a way to look at the pros/cons of compiler upgrades:

1. What are the advantages to updating the compiler?
   - Barriers to development are reduced.
   - Minimizes the bitrot exposure to anyone working on boards with more modern chips
   - Minimizes bug exposure to anyone working on boards with more modern chips
   - Compiler upgrades are inevitable, unless a project's maintainers formally intend never to upgrade the compiler. Assuming that's not the case, the closer a project tracks the latest compilers, the less work is required.
   - Presumably, the new compiler fixes things or has optimizations the old compiler does not. So generally we can expect life gets easier with more modern compilers.

2. What are the disadvantages? 
   - It takes project maintainer time to do the work and testing
   - Something could in theory go wrong.
     - At our STM32-based autopilot project-- mission critical because the drone would crash if the firmware failed-- we never had an issue with upgrading the ARM compiler. We generally did it 6 months or so after a release, in order to make sure that newly released compiler had time to be thoroughly tested by others in less sensitive applications.

From an anecdotal perspective, I don't think I've ever been involved in a project which regretted updating the compiler. I have been in ones where the targeted compiler was so ancient that it became all-but-impossible to upgrade it.

**Comment by iltis42** [comment]
esp-idf > 4.3 unfortunately comes with a open bug in the I2C transmission (read errors) so can't be used at that time:
https://github.com/espressif/esp-idf/issues/7781

**Comment by hjr** [comment]
@kubark42, nope, I really do not understand your point. You expressed the wish to have a more recent esp32, the S3 on XCV hardware. But you just argue for the SDK achievements > rev.4.3.  I missed the point that we can achieve with an S3 chip compared to the current one.

**Comment by kubark42** [comment]
@hjr the ability to use a wider selection of Espressif's line of chips is the benefit. I'm not sure if there's any difference which would be enjoyed with any of the currently available chips. The S3's FPU reportedly isn't much better than the ESP32's. The newly-announced P4 looks like it could offer something more, but that's a ways out.

@iltis42 that's unfortunate! Thanks for linking the bug report, I read through it and I'm more than a little bit shocked that 1) this problem exists and 2) it's been ignored for almost 2 years. Sounds like you really gave it your all and came out empty handed.

**Comment by hjr** [comment]
Thx for the info on S3 benefits. But yes, using a recent SDK version is generally advised.
