### ISSUE TITLE
[Feature request] Debug screen

### ISSUE THREAD

**Issue by kubark42** [iltis42/XCVario#241]
Just got my two units, they're great. The OTA update for the firmware is just awesome. I notice, as I play around with them on the bench, that there's no debug screen I can find. It would be nice to have a series of debug screens, accessible via a click on the knob, which show various internal datapoints. Things like:

 - measured pressure
 - measured IMU data
 - IMU temperature, setpoint, and self-heating duty cycle
 - compass data
 - CANbus message ID history
 - input pin status
 - free heap/stack/flash
 - etc...

If this sounds like something you'd like, I'm happy to do most of the lifting here if someone can provide the initial scaffold; e.g. a new UI page, accessible via a knob click, with a single letter of text on it. Once I see how to add one thing, I can abstract that out to adding many things.

**Comment by iltis42** [comment]
The measured pressures are part of the NMEA protocols e.g. Openvario(1), and can be seen in the XCVario Data Monitor or XCSoar Monitor. There is also a "Leak Test" debug screen, printing raw the pressures measured for 120 seconds. Press rotary button when the selftest ends and hold it, the this screen opens. 
The IMU data (gyro and accelerator X/Y/Z) is part of the $WIND NMEA sentence, that can be enabled (last 6 fields). 
IMU temperature can be seen, in XCV-23 hardware, setpoint is in "AHRS Temp Control".  Delta and PWM can be enable on console by enabling LOGs here:  https://github.com/iltis42/XCVario/blob/master/components/MPUdriver/src/MPU.cpp#L149
Compass data is part of $WIND sentence.
CANbus info can be seen from Wireless->Monitor->CAN Bus (binary and ascii mode avail).
Input pin status is directly visible by the feature it triggers, e.g. gear warning. 
Heap is printed regularly on console, if stack is low in critical tasks there is as well a warning. 

One page will not be enough IMHO to print all those things, and a momentary value won't be helpful either, some live from history (e.g. by NMEA logs), some needed a max/min capture, e.g. pressure or stack, some needed a continuous log, e.g. serial or CAN Bus data for debugging. 

1)
https://xcvario.com/wp-content/uploads/2023/07/Handbuch-E-23.0716.pdf#%5B%7B%22num%22%3A499%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C28.8%2C423.441%2C0%5D

**Comment by kubark42** [comment]
That's cool stuff, thanks for taking the time to point me toward it all.

Let me suggest, however, that those fill a different need. One thing I've learned from being a roboticist is that more data is always good. There are several debug cases which would not be covered by the above techniques:

- A pilot who is trying to troubleshoot IMU hardware, but does not have the skill to build his/her own firmware. (The use case is a pilot who changes airbases from, e.g. Franconia NH to Marfa, TX and is running into issues with the temperature stabilization)
- A pilot who is trying to diagnose issues in the air, where the ability to monitor a serial stream is challenging
- A pilot who already is using the output data-stream for communication with another device, and does not wish to reconfigure, perhaps because the incoming data from the peripheral is required.
- A pilot who wants to focus on just the values in question, and not drink from an NMEA firehose.
- A pilot who wants the raw compass data, before correction, in order to find a good place for the magnetometer installation
- A pilot who is installing new hardware, i.e. gear selector, and trying to understand why it's not working. Is it a sensor problem, a firmware problem, or a configuration problem? Knowing what the pin sees dramatically reduces debugging time, as it puts a fundamental limit on where the problem could be.
- A pilot who experiences glitches but does not have a USB connection to the device, either because of concern of voiding the warranty (the serial number sticker by design occludes the port) or simply not having space behind the instrument panel.

I agree that one page would not be enough for all. And in many cases, a single page isn't necessarily the correct approach. I see that more as a limitation of what can be done than a reason not to do it. It's amazing what we can figure out about advanced sensor fusion algorithms (e.g. all the wonderful flavors of non-linear observers) by staring at sensor data.

**Comment by iltis42** [comment]
There are not any architectural reasons, you are welcome to contribute to those debug screens. Maybe 70% i guess should be already covered, even raw compass data (forgot to mention before), for the rest yes i see there is a gap that might easily be closed.
