### ISSUE TITLE
BLE works on occasion, but is not robust

### ISSUE THREAD

**Issue by kubark42** [iltis42/XCVario#242]
**Describe the bug**

Using BLE on XCVario seems to be flaky. The thing is, I don't understand why as it looks like the BLE code comes almost directly from an example sketch from Expressif. When I run the same example sketch inside the Arduino framework, on a separate ESP32 Wemos board, I get a very solid connection.

The debug stream at `idf.py -p /dev/tty.usbserial-110 monitor` doesn't seem to give any extra information.

Using nRF Connect, I can see that the connection simply times out, with a GATT_ERROR = 133. It works one time out of 10, and it requires a power cycle between each attempt.

Perhaps there's something going wrong with a FreeRTOS task priority?

**Comment by iltis42** [comment]
BLE is not an official feature, its experimental at that time and may behave like this for the moment. Your Arduino Framework might use a different idf version. BLE prio's are part of the idf and can't be set externally.

**Comment by kubark42** [comment]
Understood. It's explained clearly in the manual that BLE is experimental and is provided as a stub for future development. 

This is a PIREP to give a better understanding of user experiences in the field. I searched around for comments on BLE and hadn't found anyone else's experience, so I thought to get the conversation going.

**Comment by DanD222** [comment]
I'm currently experiencing an issue with BLE that I'm not able to see the device on either Android or iOS.

I was able to connect to XCVario on iOS at one point in the summer; however, I've now tried a firmware version from April 2023, and the issue persisted - the XCVario wasn't visible to devices in the BLE wireless configuration.

**Comment by iltis42** [comment]
Nothing has been changed from in XCVario BLE point of view. 97% from BLE comes from espressif library. IMHO the BLE implementation there is not as stable as classic bluetooth, i can confirm also with other devices, it may be visible and connect once well, and once simply not. From application API there is very much we can do different. 
The used ESP32 modules PCB antenna can't be changed, works well with classic BT but with BLE i see others fighting with similar problems:
https://github.com/espressif/arduino-esp32/issues/7532
https://www.esp32.com/viewtopic.php?t=32446

**Comment by DanD222** [comment]
OK, thanks for the info!
