### ISSUE TITLE
Advanced AHRS Screen. Add Speed and Altimeter tape

### ISSUE THREAD

**Issue by XCNav** [iltis42/XCVario#250]
![images (8)~2](https://github.com/iltis42/XCVario/assets/78668199/43f49bfa-eb33-4c2c-b179-0a73928425a3)
Picture for schematic understanding only

Adding a transparent speed and altitude tape in airliner style on AHRS page would help to ease instrument scan in case of an possible escape from anunintentionally ifr scenario.
Soeed left side, altitude on the right.

**Comment by iltis42** [comment]
This is not possible with the SPI serial interface and due to memory constraints of ESP32 module.

**Comment by brightproject** [comment]
Good day @XCNav 
I tried to make an artificial horizon using the library [TFT_eSPI](https://github.com/Bodmer/TFT_eSPI)

![huVVer_freeRTOS_2](https://github.com/user-attachments/assets/6994c945-a3f4-4474-8bb8-e18262c1d67e)

Also now I'm trying to improve the image quality using the [lvgl](https://github.com/lvgl/lvgl) library.

![artifical](https://github.com/user-attachments/assets/7972c28d-513d-464c-a31d-65e9b6a21117)
