### ISSUE TITLE
Ballast und Bugs werden gegenseitig synchronisiert (aus dem Handbuch)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#31]
Auf der Version 21.0331-18 werden Bugs und Ballast nicht zum Wifi-Client 2. Gerät synchronisiert.

**Comment by iltis42** [comment]
Ballast und Bugs werden in dieser Version zum und vom Client und auch zum und vom Navi syncronisiert:
https://github.com/iltis42/XCVario/blob/master/images/sensor-21.0428-1203.bin
