### ISSUE TITLE
Airfield elevation setup for large value changes should be improved

### ISSUE THREAD

**Issue by speed-axel** [iltis42/XCVario#318]
If I have to change the airfield elevation over 100m and more, it is only possile in single meter steps by turning the rotary switch. I would wish me the following:

o turning the rotary switch slowly, it change the altitude per single meter
o turning the rotary switch fast, it change the altitude per 25 meters

**Comment by iltis42** [comment]
With the current framework a dynamic behavior for steps is not possible, this was a bigger change. If you want to try a pull request for this, you are welcome. 
The normal procedure is to enter airfield elevation for the place you are, is only to be done once, and the procedure we have is acceptable for this.

**Comment by speed-axel** [comment]
I just made a pull request for dynamic behavior of rotary.

**Comment by iltis42** [comment]
Closed by merge PR from @speed-axel here: https://github.com/iltis42/XCVario/pull/319, tested and works great! 
Very easy now by twisting faster to cover a big span.
