### ISSUE TITLE
Ballast Setting (improvement)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#32]
I would like to see the wingload displayed in the setup menu behind the Ballast setting. The % ballast does not give a clue on which wingload the glider is configured, but as of my understanding that is exactly what you want to achieve: Put the glider to the desired wingload. The display could look like this.
QNH ...
Ballast: 48kg/m^2 (40l)
Bugs. ....

**Comment by iltis42** [comment]
The wingload in the desired kg/m^2 is visible by entering the ballast setup, beside ballast in liters plus percentage of load increase. 
So at putting time of desired wingload the information is present.
