### ISSUE TITLE
No audio warning for gear and flarm alert (3) 

### ISSUE THREAD

**Issue by Sundown3867** [iltis42/XCVario#320]
Gear warning and Flarm alert 3 generate only click sound

**To Reproduce*
Activate gear warning or Flarm warning simulation

Runing latest (24-0410-1849) release

**Comment by iltis42** [comment]
Please crosscheck "Max volume" setting. If set to 60% in Audio -> Volume options, the issue should not happen. If it does, it is a hardware problem in the digital amplifier, in that case we offer warranty repair.

**Comment by Sundown3867** [comment]
Thank you for the reply. Volume setting < 60 can be the the reason here. I
will check as soon as I get to the ship and report back

Dne st 24. 4. 2024 22:44 uživatel Eckhard Völlm ***@***.***>
napsal:

**Comment by Sundown3867** [comment]
I tested this weekend and found that setting volume >60 did not unfortunately solved the issue.
That looks like problem vith digital amp you mentioned. As the vario sound is OK and season has started I will deal with it at the autumn (with probable upgrade to 2023 version :-)). I will do the last test with older fw release as last year mentioned sounds worked ok.

**Comment by iltis42** [comment]
Okay sure, guess in your comment >60 was a typo, max 60 or <=60 was correct ;)
Either return it for repair later, we will handle this by warranty of course, or go for an upgrade at that time as you like.
