### ISSUE TITLE
Gear warning gets breaks down if using $g,w commands and pages are switched.

### ISSUE THREAD

**Issue by mbellorini** [iltis42/XCVario#321]
Thanks for your excellent work with XcVario!!!

I found an issue here. It's minor I guess, but if at least the "ugly case" could be resolved somewhen it would be appreciated.

100% reproducible with Software 24.0410

The good case:

I use the $g,w1 and $g,w0 commands to activate/deactivate the gear warning. That works perfectly when always staying on the main page. On the main page $g,w1 will make the alarm appear both accustically and visually and it all persists until the $g,w0 command is received. The procedure can be repeated as desired. Perfect behaviour

The not-so-good case:

If I am on **either the g-force or horizon page** it looks less good. $g,w1 will activate the alarm accustically and visually. The visual part disappears after approximaty 0.5 seconds. The accustic part remains which is good. $g,w0 will stop the accustic warning. The procedure can be repeated as desired. Since the accustic alarm remains the behaviour is still quite ok albeit somehow unexpected.

The ugly case:

If **I switch pages while the alarm is active** the gear warning functionality has a complete breakdown.  $g,w1 will no longer work until the XcVario is booted. So a Gear-up condition would no long warned of.

Switching pages while the gear alarm is **not active** has no negative impact
It seems as if it does not matter between what pages (main, g-force, horizon) are switched.

Thanks, Marcel

**Comment by iltis42** [comment]
Sounds reasonable, and yes switching pages should not take place at active alarm, will look for a solution asap.

**Comment by iltis42** [comment]
I think the issue is more clearer now. The observed effect is the feature to acknowledge a an active gear warning alarm.  Its made and to holddown a new alarm for a couple of minutes and is a wellknown procedure in to acknowlege alarms in cockpits in many gadgets. As shown in code here (1) and also described in handbook (2) (where i pointed this out in bold now and made it a bit clearer). The tick period is 20 mS and 25000 ticks means = 25000*20 mS or 500 second's downtime for the gear warning alarm. So once the alarm is triggered, either by $g,w or the input pin as dedicated for this purpose, it won't fire again for a period of time. 

1)
![image](https://github.com/iltis42/XCVario/assets/34288016/cd6ae60f-db03-4c8f-a06b-11637931705f)

2)
![image](https://github.com/iltis42/XCVario/assets/34288016/a7f737ed-2b66-462f-b375-39055037bef0)

**Comment by mbellorini** [comment]
Ah ok, the short push is both a "page switch" and a "gear alarm confirmation". That is reasonable. If this is "works as designed" the issue can be closed. 

Fun Fact: If its 500s (you may want to change the comment in the code, 5 Min = 300s) my XcVario is somehow "busy". It took over 9 Minutes (>540s) on my device instead of 500s. But then: If I have my newly aquired compass connected to XcVario the device seems to get even a lot more busy. I see that by observing the blinking red-bar of the flap warner. Without the Compass connected it blinks regularly. With the compass connected it starts to blink nervously. The suspicion of "busy" is supported by the fact that with the compass connected the 9 Minute time described above goes up to over 12 Minutes. It's connecting/disconnecting the compass that makes the difference, I did not change any configuration during tests. Hope the basic functionality of the device is not compromised by that busy condition.

No need for action now, just wanted to let you know. Maybe I'll do some more experiments next week since my setup is probably a bit unusual as I have now used nearly all features available :)

Thanks for the investigation!

Marcel

**Comment by iltis42** [comment]
Yes the observed blinking effect from addittional load can be explained as the loop turnaround is de facto somewhat longer as to that 20 mS delay as other tasks processing time gets added in that loop and the display task is not running at the highest priority, there are some more time critical things, like to get round with all the calculations for compass, S2F, vario, etc.
Comment is changed, changeset below, issue clarified and closed. 

https://github.com/iltis42/XCVario/commit/d81f528be2a939a8e82b98c674e0c87ef49a5501

**Comment by iltis42** [comment]
But thinking that twice, of course there is way to handle the blinking better, the following changeset covers a constant 3 Hz blinking triggered by a system millis() counter expiration:
https://github.com/iltis42/XCVario/commit/0dc58ade21409f36d1f26150645529170986a670
