### ISSUE TITLE
Bugs setting (improvement)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#33]
Glider performance degradation due to bugs and the common way, or at least the xcsoar way, to depict it with a percentae number from 0% up to 50% might be a way to go for most cases, even not very scientific.
I still would like to go with just the "%" sign as unit, like.
Ballast: ...
Bugs: 4%

just skip the repetition of "bugs".

**Comment by iltis42** [comment]
This is already implemented by the pull for g-load in flap optimum.
