### ISSUE TITLE
Garbled flap indicator. (21.0331-18)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#37]
Flap indicator on master and client changes when magnetic heading is changing.

Master client setup equipped with master connected to a magnetic sensor (S2) and setup for flap sensor and magnetic sensor.
1. Configure client to also enable the flap indicator
2. Move magnetic sensor
3. See the heading on master reacting properly, no heading indicated on client.
4. See the flap indicator on master and client moving erratic, but in sync.

Would expect the flap indicator not to move, because no sensor is connected.

**Comment by iltis42** [comment]
Magnetic heading and also wind information is not yet available at this moment for the client, this is planned for Q2/21 after wind calculation delivers acceptable results.

**Comment by iltis42** [comment]
Garbling now also be okay now with latest build: 
https://github.com/iltis42/XCVario/blob/master/images/sensor-21.0428-1203.bin
