### ISSUE TITLE
Crash on setting the flap sensor choice. (21.0331-18)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#38]
When selecting the proper flap sensor gpio IO-34, the display stopped updating and the vario rebooted.

Did not manage to reproduce.
1. Master & Wifi client setup, both configured to flap enabled.
2. Flap sensor connected to client S2.
3. Enter setup and choose the IO-34, which the sensor is actually connected to.
4. Press the rotary.
5. Vario reboots

Liked to check on if the client would display the flap sensor readout if directly connected. It does actually, when tried a second time.

**Comment by iltis42** [comment]
This can't be reproduced with the latest binary and is considered to be already fixed.
