### ISSUE TITLE
s2f switch for two seater setup (improvement).

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#40]
As of what i have seen in two seaters it makes much sense to have the client display switching in-between vario and s2f display at the same moment, as it also does not make sense to have vario and s2f tone at the same time blasting through the cockpit. 
The latter is nicely implemented, but I would expect that the vario/s2f switching configuration from master would automatically  apply for the client device.

**Comment by iltis42** [comment]
The vario/s2f is synchronized with latest builds now from master by cruise bit in Cambridge or XCVario protocol in realtime, so this issue shall be fulfilled.
