### ISSUE TITLE
Client configuration for glider polar inherited from master (improvement)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#41]
I'd like to see the change on polar settings on the master automatically being used from a client display. Currently the client need active attention to be setup the same way. 
I would rather expect to have the polar setting transferred when registering to the master, even if the client's flash representation of those config items is untouched.

**Comment by iltis42** [comment]
Glider polar is mostly a static thing, and tuning those parameters in flight a very special case. Consider this with a low prio.

**Comment by iltis42** [comment]
There is a new generic mechanism to sync data from master to client and already applied to polar settings:
https://github.com/iltis42/XCVario/commit/45458689562438a36e03a81129daaa042c5fee45
The mechanism is prepared for a sync from client to master (or both) as well, and may be extendent for volatile data (no stored to flash), to cover data exchange of volatile data (sensor data, etc), between the devices.
