### ISSUE TITLE
Crashes on start after selecting student mode

### ISSUE THREAD

**Issue by CalvinSchwartz** [iltis42/XCVario#59]
**Describe the bug**
After updating to the current version and a successful reboot the student mode was selected.
After reboot the device passes the selftest and allows the selection of an QNH.
When the selection of QNH is confirmed by pressing the button the Vario display appears. There's no movement/change in display content and after 2-3 seconds the speaker produces a constant tone and the device reboots.
**To Reproduce**
1. Enable Student Mode
2. Reboot
3. Select QNH

**Expected behavior**
No crash

**Screenshots**
None

**Additional context**
Possible solution: Open the device and flash it again by using the internal USB Port.
Is it maybe possible to disable the student mode using a serial monitor (e.g. Arduino IDE) and send a command?
Or temporarily one line to the code to disable the student mode during startup and afterwards flash the regular firmware?
Is there a better solution than this? Disabling the student mode is not possible because the device doesn't boot completely.

**Comment by CalvinSchwartz** [comment]
[log.txt](https://github.com/iltis42/XCVario/files/6602961/log.txt)
Log file. Situation:
ESP boot complete and waits for QNH selection. Button is pressed, Vario display appears, reboots. Waiting untill the reboot is complete.

**Comment by CalvinSchwartz** [comment]
After flashing the device and again enabling the student mode the device runs exactly as it should. Therefore it's not clear why this issue occured.
Anyway, here's the complete log file, Error occurs at line 447.
[ESP_log.txt](https://github.com/iltis42/XCVario/files/6618522/ESP_log.txt)

Thanks to Iltis42 for the fast response and help via Email!

**Comment by iltis42** [comment]
The issue looks like to be linked with the Flap Display, that is the last printout in the trace, and IMHO the only reliable we have. The backtrace looks like the local build not 100% match the running image and might be misleading.
The upgrade from an older version preserving all the previous configuration normally works, hence remains a challenge and might not work in all cases. There might be settings that clash with a new software load. To have a backdoor in that case to recover, thej config can be erased as send by email. The incidence may be a good reason to add a new feature to wipe settings in an early boot phase e.g. by a pressing rotary and confirm a clean start at a certain stage.

**Comment by iltis42** [comment]
As the issue could be resolved after clearing to factory defaults, requiring some tools to be installed, a new option has now been provided in the software download screen "Factory Reset", that can be reached by shortcut (press rotary when first line with version info is printed):

![Screenshot_20210610-155713](https://user-images.githubusercontent.com/34288016/121548017-f4c68000-ca0c-11eb-8278-82db633e4458.jpg)

The issue is considered as closed with this means so far.
