### ISSUE TITLE
[Feature request] Frequency dependent volume adjustment

### ISSUE THREAD

**Issue by Thum** [iltis42/XCVario#61]
In my installation (using an external speaker) setting the volume to a level that sink and weak climb rates (say below 1 m/s) are clearly audible high climb rates (4..5 m/s) become uncomfortably loud.

Of course this may depend on the frequency characteristics of my external speaker but may also originate in the frequency-dependent sensitivity of the human ear.  I think it would be great with a frequency dependent volume adjustment.

A few thoughts on how this could be achieved (I have not carried out any experiments though): 
One could e.g. base upon the A-characteristics used in noise measurements.  Using Ra(f) as given in http://www.sengpielaudio.com/BerechnungDerBewertungsfilter.pdf one could set the frequency dependent volume in the form

   v(a,f) = v_0 * (1 + a*Ra(f_0)/Ra(f) ) / (1+a)

(*v_0* being the volume setting defined by the rotary, *0 <= a* is the new proposed adjustment parameter and *f_0* the center frequency of the the generator). Setting *a=0* reproduces the current behavior *v(0,f) = v_0* and also *v(a,f_0) = v_0*.  Higher values of *a* activate the frequency dependent volume setting where lower frequencies are output at a higher amplitude than higher frequencies up to around 2..3 kHz slightly increasing again at higher frequencies. 

With standard settings (center=500 Hz, octaves=2.0) and a=1 one would arive at an (increased) volume level of +43% at 250 Hz and a -16% (decreased) level a 1 kHz, -20% at 2 kHz and 4 kHz (at 8kHz it would rise again to around -10%).

Ra(f) defines the amplitude of the sound. So in theory the above assumes that the volume parameter adjustment should be proportional to the relative amplitude changes.  I don't know whether this assumption is correct or not, after all the volume setting is just some parameter of the amplifier logic. So may be one needs another scaling than Ra(f_0)/Ra(f).

Dirk

**Comment by iltis42** [comment]
Hi Dirk, 
sure your observation is exactly right and human ear is roughly 10dB (and that's a lot) more sensitive at 3000-4000 Hz than at 500 Hz, and together with your speaker characteristics that may be less efficient at lower frequencies, higher frequencies may result like this. The speaker inside the variometer has carefully be choosen for best linear frequency characteristic, remains the human ear.
Another thing to consider is that this may also be even desired that higher climb rates are more loud that lower ones, and should drag more attention. One workaround was to lower the frequency range, e.g. to 1.5 instead of 2.0 octaves in Audio/Tone Style settings to minimize the effect. There is still the chopping that clearly depends on the climb value, and indicates well high climb values, even the tone frequency is not too high. (We may even consider to lower the config limit here to 1.2 either).
You may with the current state also try this, if this may already help for that.
Regarding an "ergonomic volume" i we call the new feature like this, the Ra filter function to crunch in XCVario is maybe a bit overkill, but as you wrote, there may be used a simple approximation or lookup table in order to do so.

**Comment by Thum** [comment]
Hi Eckard,
thank you. Yes, I already considered to reduce the frequency range and also to adjust the center freq. 
I will try it on the next flights.

Concerning the Ra() function you are right of course. My suggestion was meant on a conceptual not implementation level.  I suppose that an n-step function with a rather low number of steps (say 10 or less) will be sufficient to produce a sufficiently smooth feeling in the noisy cockpit environment (hifi enthusiasts probably prefer other environments). The volume itself is controlled by 127 steps, if I see it correctly. 10 or 20 % correction range are at most 25 steps anyway. Since frequency changes are certainly far more frequent than changes in the volume setting it is probably most efficient to precompute the ergonomic volume correction levels when changing the volume and using (possibly volume *v_0* dependent) discretized frequency values as index. Then one only needs to compute the discretized frequency value and adjust the volume only if it has changed.

**Comment by iltis42** [comment]
There is no problem to implement a function that approximates the required curve.
According to the diagram of the following masterthesis on page 25:
https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj62YfOsrvxAhXFlosKHdUsAbcQFjADegQIAxAD&url=https%3A%2F%2Fuol.de%2Ffileadmin%2Fuser_upload%2Fstudg%2Fhua%2Fdownload%2FMasterarbeit_J.-H.Schmidt.pdf&usg=AOvVaw1Hrk0WDkm-ZXdWy1n1asJi
we may even approximate this with a linear function looking at logarithmic scales, when we assume that 8 kHz we will never reach with the audio (default setting won't), and typically more that 4 kHz does not sound well, so we may ignore this. 
Starting at middle frequency of 500 Hz, a duplication of frequency comes along with about 2.5 dB less volume we need, half frequency means to increase volume by that factor. Note that if vario operates at full volume, there is only adjustment to lower values possible. We may take this "2.5 dB" as a default for the behavior as we wish to mimic human ear sensitivity, plus make it configurable.  0 dB would mean there is no adjustment, same as today. -2.5 dB would mean the reverse operation, e.g. if your ear cannot well cope with higher frequencies (typical at age > 60), you may even rise the volume of the higher beeps.
What do you think about this idea ?

**Comment by iltis42** [comment]
The following changeset's covers the requested feature:
https://github.com/iltis42/XCVario/commit/7b3311f2c71d55542d3caece11920d057348422a
https://github.com/iltis42/XCVario/commit/ce33ebb4dbaa9a2deeb17726a9c677d5b79c731a

There is a new parameter under "Audio/Frequency Response" that is setup per as default 30% what is about 2.5 dB in terms of volume. So the beneficial feature is enabled by default, and can be deactivated by setting there 0%. 
The feature will come with the next release.

**Comment by Thum** [comment]
Hi Eckhard,
I think this looks good. I'm not sure whether the lower sensibility to higher frequencies at higher ages will really be a factor here wrt negative settings. As far as I know this concerns typically rather high frequencies (say > 8 kHz). Though (not only) my ears are at age > 60  I won't need this currently :-).
But having this option is certainly not bad be it only to be able to adjust for (external) speaker characteristics.
Actually as I said before, I tried with a shifted center frequency (650 Hz) and reduced range (octave=1.5) last weekend. This was clearly better than the default settings but at higher climb rates I still reduced the volume a bit. I really welcome this new feature.
On the other hand lower freqs were still harder to hear. But I prefer to hear the chopped sound anyway.

I'm really impressed how quickly you added this feature, thank you.

**Comment by iltis42** [comment]
The feature wasn't really complex, and improves things. I had that in mind long ago, but priorities before shifted that, but now the right time was there to work on that.  
For sure the speaker has also impact, there is frequency response of course in small speakers, esp. lower frequencies are not as loud as higher ones. An external speaker with bigger diameter and more efficiency may be better there, hence with this feature also the internal speaker improves audibility at low frequencies when volume setting is not already close to max. Depends on the noise in the cockpit of course, my glider has a loud ventilation, when i open that at cruising speed, i need also to adjust volume.
Another feature in the pipeline by the way, increasing volume at higher speed ;)
Reducing the octaves makes the Vario sound less aggressive but also a bit tired at high climb rates. I think the default setting with 2 octaves is not too bad. Lets play with the new factor for frequency response. 30% should well fit human ear, hence human's have of course tolerances either.
The build containing the new feature is through.
https://github.com/iltis42/XCVario/blob/master/images/sensor-21.0629-1316.bin

**Comment by Thum** [comment]
Yes, the default setting is fine and with the new feature I'll go back to that. I'll check this version out, but next weekend I've got on-call duty, so I hope for the following weekend.

**Comment by Thum** [comment]
Yesterday, I finally could test it (though not extensively yet - too low climb rates most of the time) and it is a real
improvement. I switched back to standard settings, so center freq 500 Hz, octaves=2 and default frequency response setting,
version was 21.0714-2057.
