### ISSUE TITLE
Airfield elevation in feet increments by +/-5m instead of +/-5 feet

### ISSUE THREAD

**Issue by nbonniere** [iltis42/XCVario#62]
With height units selected as feet, the airfield elevation adjustment increments by +/-5m instead of +/-5 feet

Suggested changes in SetupMenu.cpp:

-------------------------------------
	String elev_unit = "m";
//	int step = 1;
	float step = 1.0;
	if( alt_unit.get() == 1 ){ // ft
//		step = 5;
		step = 5.0/Units::meters2feet(1);
	}

-------------------------------------
	float elevp = elevation.get();
	if( alt_unit.get() == 0 ){ // m
		u = "m";
		p->ucg->printf("%4d %s ", (int)(elevp+0.5), u.c_str() );
	}
	else {
		u = "ft";
//		elevp = elevp*3.28084;
		elevp = Units::meters2feet(elevp);
		p->ucg->printf("%4d %s ", ((int)((elevp+2.5)/5))*5, u.c_str() );		
	}
//		p->ucg->printf("%4d %s ", (int)(elevp+0.5), u.c_str() );

**Comment by iltis42** [comment]
Will come with next build and release, your proposal works great, the following changeset covers your proposal:
https://github.com/iltis42/XCVario/commit/4ac3e583783df671288f746ca81c405c826e6b1e
Thanks for reporting and welcome to bring in changes by pull request's what makes it easy to integrate.
Closed issue.

**Comment by nbonniere** [comment]
Not fixed quite right; separate printf needed, round to 0.5 m or round to 2.5 ft.  See original suggestion with two separate printf.

for feet, Need:   p->ucg->printf("%4d %s ", ((int)((elevp+2.5)/5))*5, u.c_str() );

but for meters, need; p->ucg->printf("%4d %s ", (int)(elevp+0.5), u.c_str() );

**Comment by iltis42** [comment]
d'accord!
We needed to distinguish rounding for both cases of course.  The new changeset covering this aspect:
https://github.com/iltis42/XCVario/commit/a4335eec73605e0af3a98e8644192003efbfb005
