### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by nferruzzi** [iltis42/XCVario#65]
would you mind to add some notes to help building the project ? I've the espressif toolchain installed (and python3, ninja + deps) but so far any attempt to build the project has failed with compiler errors

ie

```/components/I2Cbus/include/i2c.h:88:54: error: 'i2c_config_t' does not name a type; did you mean 'gpio_config_t'?```

and, just in case, what is your development platform of choice ? Im on linux and mac but testing on mac atm

thanks in advance

**Comment by iltis42** [comment]
Sure, devlopment platform stable version release-v4.3 is used, see also:
https://github.com/iltis42/XCVario/blob/master/README.txt
As clarified also per email, switch to 4.3 solved the problem.
