### ISSUE TITLE
Easier firmware update procedure

### ISSUE THREAD

**Issue by lordfolken** [iltis42/XCVario#98]
**Describe the bug**
Current procedure for firmware updates, requires you to download the firmware file with a 3rd party device. Then upload it via browser to the vario meter. 

**Expected behavior**
Option 1:
 - Start the vario in wifi client mode (connects to hotspot)
 - Go to the firmware update page
 - Download the firmware directly on the device from a well known preconfigured url (https://xcvario.de/firmware/current.fw)

Option 2:
 - Extend the XCVario Protocol to allow updating the firmware via remote device (E.g. xcsoar)

**Comment by iltis42** [comment]
The idea is good, but has been thrown during design, as this requires to enter WiFi credentials from hotspot, what is not really possible with single rotary button or really cumbersome rotating char by char until the whole word is in. More easy for users: Use hotspot or mobile connection on your mobile for download that is already configured for file download, this can even be done at home, then in a second step upload XCVario, this is more quick and smart in my opinion.
Another advantage: The current procedure will work even in a place where network connection is bad or does not exist. No internet connectivity required, just bring the file on your mobile.
Unless there is a better idea than to enter WiFi credentials via rotary, i tend to close this here.

**Comment by lordfolken** [comment]
I understand. 
My usecase would be that wifi is anyway active on my phone, as i upload tracking data and get weatherdata over 4g distributed to openvario. 

My ODBII adapter in my car, can be booted into a wifi hotspot by holding down a button. You then connect to this wifi hotspot (labeled on the back of the device) and there you have a webpage where you can configure the wifi client, wifi and password. 

But i understand if you don't want to spend time on this. :) I can live with the current procedure.

**Comment by iltis42** [comment]
I think the idea is okay to do the same as the OBDII adapter does, why not configuring SID and Password within the today's OTA Update screen as a second alternative for Software Update to do exactly what you want. This would also help me to keep dozens of devices on my desk uptodate. 
And once configured, we may add a second point in the Software-Update Menu, like "Auto WiFi Update", maybe plus some shortcut during boot to reach that what does exactly what you want.
Of course this can't be used in the Outback of Australia or Namibia or in a Germany countryside hangar, somehow mostly a black hole in terms of network connectivity at the most beautiful places were we fly. 
Hence nothing speaks against a second option to do that. So i consider this as a think we can do over the long winter, and so i have reopened it!

**Comment by volkmarnissen** [comment]
In order to get weather information in xcsoar, the Wifi Client mode is really helpful.
So, it makes sense make it "end user compatible".
Additionially, it makes updates very simple.

**Comment by iltis42** [comment]
The Wifi Client mode in this ticket is considered for the Software Update only, not for the variometer mode.
In variometer mode, using WiFi Client connected e.g. to a personal hotspot seems not a good idea at the moment, as this way of connection is mainly made to route the Internet connection to a secondary device. Meanwhile things like volume limit or auto termination if no more device is listening might be possible to be disabled in hotspot configuration, they may automatically time out after a period of time so e.g. after 60 minutes without an option to disable, and if internet connection fails (and there is no warranty of a continuous signal in flight), they will drop the personal hotspot, maybe to save energy automatically. 
As of this drawbacks, WiFi Client to an external internet device is considered as not a usable, and btw kindly considered as off topic in the firmware update issue here.

**Comment by Nimbus4M** [comment]
What do you think of the idea of also displaying the web server address http://192.168.0.1 via QR code, so that lazy people don't have to type. You could also transfer the correct WLAN to the device using a QR code instruction (since Android10) ;-)

**Comment by iltis42** [comment]
Not so much as too resource intensive, better preserve this space for in flight features.

**Comment by volkmarnissen** [comment]
The QR code could as well be in the manual. This is nearly no effort and no resources are wasted.
Or you could send a sticker showing the QR code and a nice logo. It could be sticked somewhere in the cockpit at a place where it doesn't distract the pilot. 
I don't update the firmware on a regular base, so I have to use the manual each time when I do it.
However, I think this has not the highest priority.

**Comment by iltis42** [comment]
Have made a QR code for WiFi here: https://www.qr-code-generator.com/solutions/wifi-qr-code/ (tapped the Wifi symbol)
that should connect to it. Scanning this with a QR code scan app on my mobile won't open the Wifi or populate on my Xiaomi mobile. Any idea what i am missing ?

![Screenshot from 2022-02-10 09-39-23](https://user-images.githubusercontent.com/34288016/153370082-dc79db54-858e-45e9-b493-43c033fdfd16.png)

**Comment by iltis42** [comment]
Procedure proposed may work on other mobiles. Nothing else we can do from XCVario repo.
